#!/bin/bash

touch the_file_with_underscores.txt
touch 'The file with spaces and Uppercase.txt'
touch 'the file with spaces - and a single dash.txt'
touch 'the file with spaces - a spaced dash _ and an arbitrary spaced underscore.txt'
