#!/usr/bin/env bash
# THIS SCRIPT NEEDS A REWRITE TO BETTER RENAME THE FUNCTIONS CALL, THEY ARE VERY DIFFICULT TO UNDERSTAND!
#
histfile="$HOME/.cache/cliphist"
placeholder="<NEWLINE>"

add_from_selection() {
  clip=$(xclip -o -selection primary | add_to_clipboard) ;}

# previous "output" command
add_to_clipboard() {
  clip=$(xclip -i -f -selection clipboard 2>/dev/null) ;}

add_to_history() {
  [ -f "$histfile" ] || notify-send "Creating $histfile"; touch $histfile
  [ -z "$clip" ] && exit 0
  multiline=$(echo "$clip" | sed ':a;N;$!ba;s/\n/'"$placeholder"'/g')
  grep -Fxq "$multiline" "$histfile" || echo "$multiline" >> "$histfile"
  notification=$(echo \"$multiline\") ;}

select_from_clipboard() {
  selection=$(tac "$histfile" | dmenu -b -l 5 -p "Clipboard history:")
  [ -n "$selection" ] && echo "$selection" | sed "s/$placeholder/\n/g" | xclip -i -selection clipboard && notification="Copied to clipboard!" ;}

case "$1" in
  h) add_from_selection && add_to_history ;;
  stdout) add_to_clipboard && add_to_history ;;
  # the put command needs to be developed
  put) echo "pasting most recent cliphist item";;
  sel) select_from_clipboard ;;
  *) printf "$0 | File: $histfile\n\nadd - copies primary selection to clipboard, and adds to history file\nout - pipe commands to copy output to clipboard, and add to history file\nsel - select from history file with dmenu and recopy!\n" ; exit 0 ;;
esac

notify-send -h string:fgcolor:#2e3440 "$notification"
