#!/bin/bash

declare -a OPTIONS=(
"monitor_office"
"monitor_presentation"
"monitor_main"
"quit"
)

CHOICE=$(printf "%s\n" "${OPTIONS[@]}" | dmenu -i -l 20 -p "Choose monitor setup:")

if [[ "$CHOICE" == "quit" ]]; then
   echo "Selection terminated." && exit 1

#elif [ -n "$CHOICE" ] && command -v "$CHOICE" > /dev/null; then
#  "$CHOICE"
elif [ "$CHOICE" ]; then
  "$CHOICE"

else
    echo "Program terminated." && exit 1
fi
