#!/bin/bash

xrandr --output eDP --mode 2256x1504 --right-of DisplayPort-11 --output DisplayPort-11 --primary --mode 2560x1440
xdotool mousemove --screen 0 1280 720
brightnessctl set 100%
nitrogen --restore
setxkbmap -layout dk
notify-send "Connected to office monitors."
