#!/bin/sh

cal_icon=""
clock=$(date '+%I')
date=$(echo "W"; date +%V; date +%m-%d)
time=$(date +"%H:%M")
#time=$(date "+%I:%M%p")

case "$clock" in
	"00") clock_icon="󱑊 " ;;
	"01") clock_icon="󱐿 " ;;
	"02") clock_icon="󱑀 " ;;
	"03") clock_icon="󱑁 " ;;
	"04") clock_icon="󱑂 " ;;
	"05") clock_icon="󱑃 " ;;
	"06") clock_icon="󱑄 " ;;
	"07") clock_icon="󱑅 " ;;
	"08") clock_icon="󱑆 " ;;
	"09") clock_icon="󱑇 " ;;
	"10") clock_icon="󱑈 " ;;
	"11") clock_icon="󱑉 " ;;
	"12") clock_icon="󱑊 " ;;
esac

case $BLOCK_BUTTON in
	1) notify-send "This Month" "$(cal | sed "s/\<$(date +'%e'|tr -d ' ')\>/<b><span color='red'>&<\/span><\/b>/")" && notify-send "Appointments" "$(calcurse -d3)" ;;
	2) setsid -f "$TERMINAL" -e calcurse ;;
	3) notify-send "󱑁  Time/date module" "\- Left click to show upcoming appointments for the next three days via \`calcurse -d3\` and show the month via \`cal\`
- Middle click opens calcurse if installed" ;;
	6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

echo -n $cal_icon " " && echo -n $date " " && echo -n $clock_icon " " && echo -n $time
#date "+%Y %B %D %I:%M%p"
