#!/usr/bin/env bash

# script to call flameshot with selective shot, adding to screenshot dir and copying to clipboard
screenshot_dir="$HOME/Pictures/screenshots/"
flameshot gui --clipboard --path "$screenshot_dir"

# find . -type f -printf "%T@ %p\n" | sort -n | cut -d' ' -f 2- | tail -n 1 | xclip -selection clipboard -t .png
# find . -type f -printf "%T@ %p\n" | sort -n | cut -d' ' -f 2- | tail -n 1 | xclip -selection clipboard -t image/png
